# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "barge-PaperMod"
license = "MIT"
licenselink = "https://github.com/ts4z/barge-hugo-PaperMod/blob/master/LICENSE"
description = "PaperMod fork for local changes"
homepage = "https://github.com/ts4z/barge.org"
demosite = "https://www.barge.org/"
tags = [
  "responsive",
  "blog",
  "clean",
  "minimal",
  "light",
  "dark",
  "fast",
  "multilingual",
  "search",
  "seo",
  "chroma",
  "personal"
]
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "twitter-cards",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search",
  "breadcrumbs",
  "reading-time",
  "word-count",
  "code-copy",
  "comments",
  "edit-post",
  "canonical-link",
  "profile-mode",
  "home-info-mode",
  "related-posts",
  "rss",
  "multiple-authors",
  "post-nav-links"
]
min_version = "0.146.0"

[author]
  name = "Tim Showalter"
  homepage = "https://github.com/ts4z"

# If porting an existing theme
[original]
  name = "hugo-PaperMod"
  author = "nanxiaobei"
  homepage = "https://github.com/adityatelange"
  repo = "https://github.com/adityatelange/hugo-PaperMod/"
